---
- name: "Installing unzip"
  apt: "pkg=unzip state=latest install_recommends=yes"
  
- name: "Making the Home Path"
  file: dest=/opt/ESB mode=0775 owner=root group=root state=directory

- name: "Downloading the ESB package and Unzip"
  unarchive:
    src: https://s3.amazonaws.com/teraesb/wso2esb-5.0.0.zip
    dest: /opt/ESB
    remote_src: yes

- name: "Making the Product home path"
  blockinfile:
    path: ~/.bashrc
    block: |
      export JAVA_HOME=/usr/lib/jvm/java-8-oracle
      export PATH=${JAVA_HOME}/bin:${PATH}
      export ESB_HOME=/opt/ESB/wso2esb-5.0.0
      export PATH=${ESB_HOME}/bin:${PATH}
    insertafter: EOF 
